/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_tagman (void);
GtkWidget* create_chooserepository (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_helpdialog (void);
