Document: tagsistant
Title: Debian tagsistant Manual
Author: <insert document author here>
Abstract: This manual describes what tagsistant is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tagsistant/tagsistant.sgml.gz

Format: postscript
Files: /usr/share/doc/tagsistant/tagsistant.ps.gz

Format: text
Files: /usr/share/doc/tagsistant/tagsistant.text.gz

Format: HTML
Index: /usr/share/doc/tagsistant/html/index.html
Files: /usr/share/doc/tagsistant/html/*.html
